src/Emploee.Web/Areas/Mpa/Models/DictionaryManage/CreateOrEditDictionaryModalViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Abp.Application.Services.Dto;
using Abp.AutoMapper;
using Abp.Runtime.Validation;
using Abp.Extensions;
using Emploee.Emploee.Dictionaries.Dtos;

namespace Emploee.Web.Areas.Mpa.Models.DictionaryManage
{
    /// <summary>
    /// 新建或编辑数据字典时使用的Viewmodel
    /// </summary>
    [AutoMap(typeof(GetDictionaryForEditOutput))]
    public class CreateOrEditDictionaryModalViewModel : GetDictionaryForEditOutput
    {
		/// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="output"></param>
	   public CreateOrEditDictionaryModalViewModel(GetDictionaryForEditOutput output)
        {
            output.MapTo(this);
        }



		 /// <summary>
        /// 是否处于编辑状态
        /// </summary>
	  public bool IsEditMode { get { return Dictionary.Id.HasValue; } }

	    
		
        /// <summary>
        /// 模糊查询字段
        /// </summary>
        public string FilterText { get; set; }

    }
}

src/Emploee.Web/Areas/Mpa/Models/DictionaryManage/DictionaryViewModel.cs
using Emploee.Emploee.Dictionaries.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Emploee.Web.Areas.Mpa.Models.DictionaryManage
{
    public class DictionaryViewModel
    {
        public string ParentCode { get; set; }

        public List<DictionaryListDto> ParentList { get; set; }

    }
}

src/Emploee.Web/Areas/Mpa/Controllers/DictionaryManageController.cs
// 项目展示地址:"http://www.ddxc.org/"
// 如果你有什么好的建议或者觉得可以加什么功能，请加QQ群：104390185大家交流沟通
// 项目展示地址:"http://www.yoyocms.com/"
//博客地址：http://www.cnblogs.com/wer-ltm/
//代码生成器帮助文档：http://www.cnblogs.com/wer-ltm/p/5777190.html
// <Author-作者>角落的白板笔</Author-作者>
// Copyright © YoYoCms@中国.2017-12-28T09:13:40. All Rights Reserved.
//<生成时间>2017-12-28T09:13:40</生成时间>
using Abp.Application.Services.Dto;
using Abp.Web.Mvc.Authorization;
using Emploee.Emploee.Dictionaries;
using Emploee.Emploee.Dictionaries.Authorization;
using Emploee.Emploee.Dictionaries.Dtos;
using Emploee.Web.Areas.Mpa.Models.DictionaryManage;
using Emploee.Web.Controllers;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Emploee.Web.Areas.Mpa.Controllers
{
    public class DictionaryManageController : EmploeeControllerBase
    {

        private readonly IDictionaryAppService _DictionaryAppService;

        public DictionaryManageController(IDictionaryAppService DictionaryAppService)
        {
            _DictionaryAppService = DictionaryAppService;
           
        }

        public  ActionResult Index()
        {
            // var model = new GetDictionaryInput {FilterText = Request.QueryString["filterText"]};

            try
            {
                var model = new DictionaryViewModel
                {
                    ParentCode = Request.QueryString["parentCode"],
                    ParentList = _DictionaryAppService.GetParentList(Request.QueryString["parentCode"])
                };


                return View(model);
            }
            catch
            {
                return   RedirectToAction("Index", "Home");
            }


           
        }

	 

			  /// <summary>
        /// 根据id获取进行编辑或者添加的用户信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
		[AbpMvcAuthorize(DictionaryAppPermissions.Dictionary_CreateDictionary,DictionaryAppPermissions.Dictionary_EditDictionary)]
        public async Task<PartialViewResult> CreateOrEditDictionaryModal(int? id,string parentCode)
        {
		var input=new NullableIdDto<int>{Id=id};
	 
                 var output=    await _DictionaryAppService.GetDictionaryForEditAsync(input);
            if (string.IsNullOrEmpty(output.Dictionary.ParentCode))
                output.Dictionary.ParentCode = parentCode;


                 var viewModel=new CreateOrEditDictionaryModalViewModel(output);


            return PartialView("_CreateOrEditDictionaryModal",viewModel);
        }
	 
       
    }
}

src/Emploee.Web/Areas/Mpa/Views/DictionaryManage/Index.cshtml
@using Abp.Web.Mvc.Extensions
@using Emploee.Emploee.Dictionaries.Authorization
@model Emploee.Web.Areas.Mpa.Models.DictionaryManage.DictionaryViewModel
@{
    ViewBag.CurrentPageName = DictionaryAppPermissions.Dictionary;
    ViewBag.Title = L("Dictionary");

}

@section Styles{
		
	  	  	  	    
}


@* 注入所需JS *@
@section Scripts
{ 
    
    <script src="~/Areas/Mpa/Views/DictionaryManage/_CreateOrEditDictionaryModal.js"></script>
    <script src="~/Areas/Mpa/Views/DictionaryManage/Index.js"></script>
}
<div class="row margin-bottom-5">
    <div class="col-xs-6">
        <div class="page-head">
            <div class="page-title">
                <h1>
                    <span>配置管理</span> 
                </h1>
            </div>
        
        </div>
    </div>
    <div class="col-xs-6 text-right">
        <button  id="ButtonReload" class="btn btn-primary blue"><i class="fa  fa-refresh"></i> @L("Refresh")</button>


        @if (IsGranted(DictionaryAppPermissions.Dictionary_CreateDictionary))
        {
            <button id="CreateNewDictionaryButton" class="btn btn-primary blue"><i class="fa fa-plus"></i> 新增配置</button>
        }
    </div>
</div>

<div class="portlet light">
 @* 通用搜索功能 *@
<div class="portlet-title portlet-title-filter">
        <div class="inputs inputs-full-width">
            <div class="portlet-input">
                <form>
                    <div class="input-group">
                        <input id="txtFilterText" class="form-control" placeholder="@L("SearchWithThreeDot")" type="text" >
                        <span class="input-group-btn">
                            <button id="GetDictionarysButton" class="btn default" type="submit"><i class="icon-magnifier"></i></button>
                            <input type="hidden" id="hidParentCode" name="hidParentCode" value="@Model.ParentCode" />
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="portlet-body">
        <div id="toolbar">
            <ul class="page-breadcrumb breadcrumb">
                <li>
                    <a href="@Url.Action("Index", "DictionaryManage")">总分类</a>
                </li>
                @foreach (var p in Model.ParentList)
                {
                    <li>
                        <i class="fa fa-circle"></i>
                        <a href="@Url.Action("Index", "DictionaryManage")?parentCode=@p.Code">@p.Name</a>
                    </li>
                }
            </ul>
        </div>
        <div id="DictionarysTable"></div>
    </div>
</div>









 

src/Emploee.Web/Areas/Mpa/Views/DictionaryManage/_CreateOrEditDictionaryModal.cshtml
@using Abp.Extensions
@using Abp.Application.Services.Dto
@using Emploee.Web.Areas.Mpa.Models.Common.Modals
@using Emploee.Web.Areas.Mpa.Models.DictionaryManage

@model CreateOrEditDictionaryModalViewModel

@* 初始化头部 *@
@Html.Partial("~/Areas/Mpa/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(Model.IsEditMode ? ("编辑" + ": " + Model.Dictionary.Name) : "新增"))


<!--html代码区域-->
<div class="modal-body">
    <form name="DictionaryInformationsForm"   role="form" novalidate class="form-validation">
 <input type="hidden" name="Id" value="@Model.Dictionary.Id" />
 <div class="row">


     <div hidden="hidden">
         @if (Model.IsEditMode)
         {
             <input type="hidden" name="Id" value="@Model.Dictionary.Id" />
         }
     </div>
     <div class="col-sm-12 ">
         <div class="form-group">
             <label class="col-sm-4 control-label">父编码</label>
             <div class="col-sm-8">
                 <input class="form-control inline w300  maxlength-handler   " type="text" value="@Model.Dictionary.ParentCode" disabled />
                 <span class="help-inline"></span>
             </div>
         </div>
     </div>
     <div class="col-sm-12 ">
         <div class="form-group">
             <label class="col-sm-4 control-label">@L("Code")</label>
             <div class="col-sm-8">
                 <input class="form-control inline w300  maxlength-handler   " type="text" value="@Model.Dictionary.Code"   />
                 <span class="help-inline"></span>
             </div>
         </div>
     </div>
     <div class="col-sm-12 ">
         <div class="form-group">
             <label class="col-sm-4 control-label">@L("Name")</label>
             <div class="col-sm-8">
                 <input class="form-control inline w300  maxlength-handler   " type="text" value="@Model.Dictionary.Name"   />
                 <span class="help-inline"></span>
             </div>
         </div>
     </div>
     <div class="col-sm-12 ">
         <div class="form-group">
             <label class="col-sm-4 control-label">值</label>
             <div class="col-sm-8">
                 <input class="form-control inline w300  maxlength-handler   " type="text" value="@Model.Dictionary.Value"   />
                 <span class="help-inline"></span>
             </div>
         </div>
     </div>
     <div class="col-sm-12 ">
         <div class="form-group">
             <label class="col-sm-4 control-label">操作</label>
             <div class="col-sm-8">
                 <input class="form-control inline w300  maxlength-handler   " type="text" value="@Model.Dictionary.OrderIndex"   />
                 <span class="help-inline"></span>
             </div>
         </div>
     </div>
     @*<div class="form-group form-md-line-input form-md-floating-label no-hint">
            <textarea name="ParentCode" auto-focus class="form-control @(Model.Dictionary.ParentCode.IsNullOrEmpty() ? "" : "edited")" 	  rows="4">@Model.Dictionary.ParentCode</textarea>
            <label> @L("ParentCode") </label>
        </div> 



      <div class="form-group form-md-line-input form-md-floating-label no-hint">
         <textarea name="Code" auto-focus class="form-control @(Model.Dictionary.Code.IsNullOrEmpty() ? "" : "edited")" required rows="4">@Model.Dictionary.Code</textarea>
         <label> @L("Code")   <span class="required"> * </span>	 	</label>
     </div>



     <div class="form-group form-md-line-input form-md-floating-label no-hint">
         <textarea name="Name" auto-focus class="form-control @(Model.Dictionary.Name.IsNullOrEmpty() ? "" : "edited")" required rows="4">@Model.Dictionary.Name</textarea>
         <label> @L("Name")   <span class="required"> * </span>	 	</label>
     </div>

     <div class="form-group form-md-line-input form-md-floating-label no-hint">
         <textarea name="Value" auto-focus class="form-control  " rows="4">@Model.Dictionary.Value</textarea>
         <label> 值    	</label>
     </div>

     <div class="form-group form-md-line-input form-md-floating-label  ">
         <input class="maxlength-handler form-control" type="text" name="OrderIndex" value="@Model.Dictionary.OrderIndex" required />
         <label>@L("OrderIndex")   <span class="required"> * </span>	 	</label>
     </div>*@


 </div>
    </form>
</div>
@Html.Partial("~/Areas/Mpa/Views/Common/Modals/_ModalFooterWithSaveAndCancel.cshtml")
 