src/Emploee.Web/Controllers/PersonHomeController.cs
using Emploee.Emploee.JobPosts;
using System.Threading.Tasks;
using System.Web.Mvc;
using Emploee.Web.Areas.Mpa.Models.JobPostManage;
namespace Emploee.Web.Controllers
{
    public class PersonHomeController : EmploeeControllerBase
    {
        private readonly IJobPostAppService _jobPostAppService;
        
         

        public PersonHomeController(IJobPostAppService jobPostAppService)
        {
            _jobPostAppService = jobPostAppService;
        }
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 根据id获取进行编辑或者添加的用户信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
         
        public async Task<ActionResult> Introduce(int? id)
        {
            if (id == null)
            {
                return null;
            }

            var output = await _jobPostAppService.GetJobIntroduce((int)id);


            var viewModel = new CreateOrEditJobPostModalViewModel(output);
            //if(viewModel.JobPost.SkillRequire!=null)
            //    viewModel.JobPost.SkillRequire= viewModel.JobPost.SkillRequire.Replace("\r\n", "<br />");
            //if (viewModel.JobPost.JobDetail != null)
            //    viewModel.JobPost.JobDetail=viewModel.JobPost.JobDetail.Replace("\r\n", "<br />");
            //if (viewModel.JobPost.Memo != null)
            //    viewModel.JobPost.Memo=viewModel.JobPost.Memo.Replace("\r\n", "<br />");
            return View("Introduce", viewModel);


        }
    }
}

src/Emploee.Web/Views/PersonHome/Introduce.cshtml
@using Emploee.Web.Navigation

@using Abp.Extensions

@using Emploee.Web.Areas.Mpa.Models.JobPostManage

@model CreateOrEditJobPostModalViewModel
@{
    ViewBag.CurrentPageName = PageNames.Frontend.Home;
}
@section Styles
{
    <link href="~/libs/layui/css/layui.css" rel="stylesheet" />
    <link href="~/libs/aliIcon/iconfont.css" rel="stylesheet" />
    <link href="~/Views/PersonHome/Introduce.css" rel="stylesheet" />

}
@section Scripts
{

    <script src="~/libs/layui/layui.js"></script>
    <script src="~/Views/PersonHome/index.js"></script>
    @*<script src="~/Views/PersonHome/Introduce.js"></script>*@
}


<div>
    <div class="margin-bottom-40 JobHigh">
        <div class=" row col-md-12 col-lg-12 col-sm-12 col-xs-12 returnBtn">

            
            <a href="javascript:history.back(-1)" class="  col-xs-4  " id="returnPage"><i class="glyphicon glyphicon-chevron-left"></i>返回</a>
        </div>
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <div class="row form-group">

                <div class="col-sm-4 JobName col-xs-4">
                    <strong>@Model.JobPost.JobName</strong>

                </div>
                <div class="col-sm-2 col-sm-offset-6 Salary  col-xs-4  col-xs-offset-4">
                    <i class="iconfont icon-xxx"></i>@Model.JobPost.SalaryMin- @Model.JobPost.SalaryMax K
                </div>
            </div>


            <div class="row form-group">

                <div class="col-sm-6 col-xs-12">
                    <span class="iconfont  icon-dizhi "></span>@Model.JobPost.JobAddress
                    <span class="iconfont  icon-gongzuonianxian-  "></span>@Model.JobPost.Experience
                    <span class="iconfont  icon-xueli  "></span>@Model.JobPost.Education
                </div>
            </div>
            <div class="row form-group">

                <hr class="hr0" />
                <div class="col-sm-4 JobName col-xs-4"> <strong>职位详情</strong></div>
                <div class="col-sm-1 JobName col-xs-2 pull-right">
                    <button class="btn " id="factory">感兴趣</button>
                </div>
            </div>

            <div class="row form-group col-md-12 col-lg-12 col-sm-12 col-xs-12">

                <div class="title JobTitle">
                    <strong> 技能要求（岗位职责）:</strong>
                </div>
                <div class="JobMemo">@Model.JobPost.SkillRequire </div>


            </div>
            <div class="row form-group col-md-12 col-lg-12 col-sm-12 col-xs-12">
                <div class="title JobTitle">
                    <strong> 职位详情（岗位要求）:</strong>
                </div>
                <div class="JobMemo">@Model.JobPost.JobDetail </div>

            </div>
            <div class="row form-group col-md-12 col-lg-12 col-sm-12 col-xs-12">
                <div class="title JobTitle">
                    <strong> 待遇:</strong>
                </div>
                <div class="JobMemo"> @Model.JobPost.Memo </div>

            </div>
            <div class="row form-group hidden  ">

                <input id="CompanyId" value="@Model.JobPost.CompanyId" />
                <input id="JobId" value="@Model.JobPost.Id" />

            </div>
            <div class="row ">
                @*公司内容*@
                <div class="layui-collapse  col-md-12 col-lg-12 col-sm-12 col-xs-12" lay-accordion>
                    <div class="layui-colla-item">
                        <h2 class="layui-colla-title">公司介绍——@Model.Company.CompanyName </h2>
                        <div class="layui-colla-content  ">
                            <div>
                                <strong>行业类型：</strong> @Model.Company.Classify
                            </div>
                            <div>
                                <strong>公司规模：</strong> @Model.Company.CompanyScale
                            </div>
                            <div>
                                <strong>融资阶段：</strong> @Model.Company.Finanicing
                            </div>
                            <div>
                                <strong>公司地址：</strong> @Model.Company.CompanyAddress
                            </div>
                            <div>
                                <strong>公司介绍：</strong> @Model.Company.CompanyIntroduce
                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </div>

    </div>
</div>

src/Emploee.Web/Views/PersonHome/index.cshtml
@using Emploee.Localization
@using Emploee.Web.Navigation
@{
    ViewBag.CurrentPageName = PageNames.Frontend.Home;
}
@section Styles
{
    @*<link href="~/libs/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="~/libs/carousel-owl-carousel/owl-carousel/owl.carousel@(CultureHelper.IsRtl ? "-rtl" : "").css" rel="stylesheet">*@
    <link href="~/libs/layui/css/layui.css" rel="stylesheet" />
    <link href="~/libs/swiper-Swiper4/dist/css/swiper.min.css" rel="stylesheet" />
    <link href="~/Views/PersonHome/index.css" rel="stylesheet" />
}
@section Scripts
{

    <script src="~/libs/layui/layui.js"></script>
    <script src="~/Views/PersonHome/index.js"></script>
}
<!-- BEGIN SERVICE BOX -->
@*<div class="swiper-container swiper-width "  >
        <div class="swiper-wrapper">

            <div class="swiper-slide">
                <a href="#" style="display:block">
                    <img src="~/libs/swiper-Swiper4/demos/images/nature-1.jpg" class="img-responsive img-rounded" />
                </a>
            </div>
            <div class="swiper-slide">
                <a href="#" style="display:block">
                    <img src="~/libs/swiper-Swiper4/demos/images/nature-2.jpg" class="img-responsive img-rounded" />
                </a>
            </div>
            <div class="swiper-slide">
                <a href="#" style="display:block">
                    <img src="~/libs/swiper-Swiper4/demos/images/nature-3.jpg" class="img-responsive img-rounded" />
                </a>
            </div>
            <div class="swiper-slide">
                <a href="#" style="display:block">
                    <img src="~/libs/swiper-Swiper4/demos/images/nature-4.jpg" class="img-responsive img-rounded" />
                </a>
            </div>

        </div>
        <!-- 如果需要分页器 -->
        <div class="swiper-pagination"></div>

        <!-- 如果需要导航按钮 -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>

    </div>*@
<button class="layui-btn" id="reloadbtn">reload</button>
<div id="layInfo">
    <div class="margin-bottom-40" id="flowContain">
        <div>
            <div class="top mytop">
                <div class="myleft">
                    <p class="job">
                        Web前段
                        <span class="label label-danger weigh">急</span>
                    </p>
                </div>
                <div class="myright">
                    北京侏罗纪开发有限公司

                </div>
            </div>
            <div class="bottom mybottom">
                <div class="bottomleft">
                    <ul>
                        <li>10-15</li>
                        <li>经验</li>
                        <li>本科</li>
                        <li>股份制</li>
                        <li>500人</li>
                    </ul>
                </div>
                <div class="bottomright">
                     
                    <a class="layui-btn layui-btn-normal layui-btn-radius layui-btn-sm clickBtn" href="@Url.Action("Introduce", "PersonHome", new {id = 5})">
                        <span class="glyphicon glyphicon-link"></span>
                        详情
                    </a>
                     
                </div>

            </div>

            <hr class="hr0" />
        </div>
        <div>
            <div class="top mytop">
                <div class="myleft">
                    <p class="job">
                        Web前段
                        <span class="label label-danger weigh">急</span>
                    </p>
                </div>
                <div class="myright">
                    北京侏罗纪开发有限公司

                </div>
            </div>
            <div class="bottom mybottom">
                <div class="bottomleft">
                    <ul>
                        <li>10-15</li>
                        <li>经验</li>
                        <li>本科</li>
                        <li>股份制</li>
                        <li>500人</li>
                    </ul>
                </div>
                <div class="bottomright">

                    <button type="button" class="layui-btn layui-btn-normal layui-btn-radius layui-btn-sm clickBtn" onclick="alert(1)">
                        <span class="glyphicon glyphicon-link"></span>
                        详情
                    </button>
                </div>

            </div>

            <hr class="hr0" />
        </div>

        <div>
            <div class="top mytop">
                <div class="myleft">
                    <p class="job">
                        Web前段
                        <span class="label label-danger weigh">急</span>
                    </p>
                </div>
                <div class="myright">
                    北京侏罗纪开发有限公司

                </div>
            </div>
            <div class="bottom mybottom">
                <div class="bottomleft">
                    <ul>
                        <li>10-15</li>
                        <li>经验</li>
                        <li>本科</li>
                        <li>股份制</li>
                        <li>500人</li>
                    </ul>
                </div>
                <div class="bottomright">

                    <button type="button" class="layui-btn layui-btn-normal layui-btn-radius layui-btn-sm clickBtn " onclick="alert(1)">
                        <span class="glyphicon glyphicon-link"></span>
                        详情
                    </button>
                </div>

            </div>

            <hr class="hr0" />
        </div>
    </div>
</div>

<div class="swiper-container swiper-width ">
    <div class="swiper-wrapper">

        <div class="swiper-slide">
            <a href="#" style="display:block">
                <img src="~/libs/swiper-Swiper4/demos/images/nature-1.jpg" class="img-responsive img-rounded" />
            </a>
        </div>
        <div class="swiper-slide">
            <a href="#" style="display:block">
                <img src="~/libs/swiper-Swiper4/demos/images/nature-2.jpg" class="img-responsive img-rounded" />
            </a>
        </div>
        <div class="swiper-slide">
            <a href="#" style="display:block">
                <img src="~/libs/swiper-Swiper4/demos/images/nature-3.jpg" class="img-responsive img-rounded" />
            </a>
        </div>
        <div class="swiper-slide">
            <a href="#" style="display:block">
                <img src="~/libs/swiper-Swiper4/demos/images/nature-4.jpg" class="img-responsive img-rounded" />
            </a>
        </div>

    </div>
    <!-- 如果需要分页器 -->
    <div class="swiper-pagination"></div>

    <!-- 如果需要导航按钮 -->
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

</div>
<!-- END CLIENTS -->
<script src="~/libs/swiper-Swiper4/dist/js/swiper.min.js"></script>
<script>
    var mySwiper = new Swiper('.swiper-container', {

        loop: true, // 循环模式选项
        //设置宽度为全屏
        centeredSlides: true,

        autoplay: {
            delay: 3000
        }, //可选选项，自动滑动
        effect: 'fade',
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },


    })
</script>